# Generated by Django 3.2.6 on 2021-09-06 11:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_device_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='online_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 6, 11, 10, 59, 94143, tzinfo=utc)),
        ),
    ]
